### ISSUE TITLE
Backend Notification Feature

### ISSUE THREAD

**Issue by jianweiiii** [rawsashimi1604/ICT2106_P2_Project#18]

**Comment by junweilam** [comment]
Start Date: 31/01/2023
End Date: 03/02/2023

**Preconditions**
- Database must be set up

**Definitions of done: **

- [ ] Able to connect to database
- [ ] Feature able to work 



![Image](https://user-images.githubusercontent.com/91267859/218014411-fc8cf0b2-aed3-41ea-a9fc-a7aa3ec630d8.png)
