### ISSUE TITLE
D1 - Team's Features & Requirements

### ISSUE THREAD

**Issue by 2102673** [rawsashimi1604/ICT2106_P2_Project#19]
# Complete Team's Features & Requirement 

Start Date: 30/01/2023
End Date: 31/01/2023

### Preconditions:
- None

### Definition of done:
- [x] Client have to confirm the Features & Requirements

**Comment by jianweiiii** [comment]
![Image](https://user-images.githubusercontent.com/91450271/218020407-25d690f2-58f2-4084-a703-97840ead2922.png)
