### ISSUE TITLE
Frontend Notification Feature

### ISSUE THREAD

**Issue by jianweiiii** [rawsashimi1604/ICT2106_P2_Project#25]

**Comment by junweilam** [comment]
Start Date: 24/01/2023
End Date: 27/01/2023

**Preconditions:**

- None

**Definition of done: **

- [ ] Frontend feature for the notification



![Image](https://user-images.githubusercontent.com/91267859/218012812-0f80524a-5c8f-4b46-979a-551f5094381a.png)
