### ISSUE TITLE
D1 - Task Assignment & Timeline

### ISSUE THREAD

**Issue by 2102673** [rawsashimi1604/ICT2106_P2_Project#29]

**Comment by junweilam** [comment]
Start Date: 07/02/2023
End Date: 08/02/2023

**Preconditions: **
- None

**Definition of done: **

- [ ] D1 Tasks Assigned
- [ ] D1 Timeline completed



![Image](https://user-images.githubusercontent.com/91267859/218016702-41027037-463e-47db-874d-8cacf885eaa9.png)
