### ISSUE TITLE
4. Software Design Evaluation

### ISSUE THREAD

**Issue by minXnub** [rawsashimi1604/ICT2106_P2_Project#36]
To be completed by 10 Feb 2023

**Comment by rb-t** [comment]
Analysis methods and design

![Image](https://user-images.githubusercontent.com/90168622/218649998-9bd4ab22-371d-41cd-b5fb-16e3f9b576b3.png)

**Comment by rb-t** [comment]
Architectural Pattern


![Image](https://user-images.githubusercontent.com/90168622/218650075-8468535d-2203-4bb9-bb5c-94372511bb9e.png)

**Comment by rb-t** [comment]
Done by 10/2/2023
