### ISSUE TITLE
Brainstorming Functional Requirements

### ISSUE THREAD

**Issue by jianweiiii** [rawsashimi1604/ICT2106_P2_Project#4]
Start Date: 14/01/23
End Date: 15/01/23

![Image](https://user-images.githubusercontent.com/94159228/218149782-c5344571-4a01-484d-bcf2-92acc6d2c517.png)
![Image](https://user-images.githubusercontent.com/94159228/218013251-0899d17b-8693-4788-b299-6f31d02caf56.png)

**Comment by nicnathaniel** [comment]
Start Date: 14/01/23
End Date: 15/01/23



![Image](https://user-images.githubusercontent.com/94159228/218013170-1224ba52-f02c-49a7-9080-4e91125a4293.png)



![Image](https://user-images.githubusercontent.com/94159228/218013251-0899d17b-8693-4788-b299-6f31d02caf56.png)
