### ISSUE TITLE
5.1 Task Assignments

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project#57]
To do:

1. Add task assignments for team members in the report

Deadline: 11 Feb 2023, 12pm

**Comment by geethika-m** [comment]
Added task assignments table inside the Appendix in the report on 10 Feb 2023.

![Image](https://user-images.githubusercontent.com/71939490/218646506-f4e16d50-126e-435c-b614-2a363ab18b43.png)

**Comment by minXnub** [comment]
Closed as completed on 11 Feb 2023
