### ISSUE TITLE
1.2 Project’s Quality Attributes

### ISSUE THREAD

**Issue by rylan98** [rawsashimi1604/ICT2106_P2_Project#58]
To do: 
1. Add in Quality attributes that the team is aiming to achieve in the design

Deadline: 11 Feb 2023, 12pm

**Comment by geethika-m** [comment]
5 quality attributes (Usability, Scalability, Conceptual Integrity, Reusability and Testability), supported with explanations, has been added inside the report before 11 Feb 2023.

**Comment by geethika-m** [comment]
Closed as completed

**Comment by rylan98** [comment]
Done by 10/2/2023
