### ISSUE TITLE
5.2 Project Timeline

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project#59]
To do:

1. Do a Gantt chart which shows the tasks and timeline for Deliverable 1.

Deadline: 11 Feb 2023, 12pm

**Comment by geethika-m** [comment]
Gantt chart added on 10 Feb 2023.

![Image](https://user-images.githubusercontent.com/71939490/218649239-f077774f-97aa-4168-b7f2-8f8cbe94539f.png)

**Comment by geethika-m** [comment]
Closed as completed

**Comment by rylan98** [comment]
Done by 10/2/2023
