### ISSUE TITLE
3.1 Software Architecture Design

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project#63]
Todo:

Draw and explain the architecture design:
1) of where the team portion sits in the module
2) of the team portion that is communicating with other parts of the overall system

![Image](https://user-images.githubusercontent.com/97349748/218650296-1ea2860b-dd86-45c0-9231-29c6e0c6860b.png)

Deadline: 11 Feb 2023, 12pm

**Comment by rb-t** [comment]
Explanation:

Our team is handling device logging and energy usage threshold limit. Each component would have an Entity and Control class in them and retrieve information through interfaces provided by each component which would be explained in detail under detailed design

Done by Feb 10
