### ISSUE TITLE
2.1 Use Case Diagram

### ISSUE THREAD

**Issue by rylan98** [rawsashimi1604/ICT2106_P2_Project#64]
Todo:

1) Use Diagram
2) Use Case descriptions

![Image](https://user-images.githubusercontent.com/97349748/218647944-29f2b068-7787-406e-9869-313b8e691902.png)

Deadline: 11 Feb 2023, 12pm

**Comment by rb-t** [comment]
UC 1 & UC 2



![Image](https://user-images.githubusercontent.com/90168622/218652717-e5a9add7-c086-48ca-8b54-b4c8f447dd4a.png)

**Comment by rb-t** [comment]
UC 2-2 , UC 3, UC 4



![Image](https://user-images.githubusercontent.com/90168622/218652759-72d2c997-a94a-4412-9ecb-04523f7f1a11.png)

**Comment by rb-t** [comment]
UC 4.1, UC 5, UC 6 



![Image](https://user-images.githubusercontent.com/90168622/218652824-f5bccbbe-4156-43c4-af85-9433d2b1d1d6.png)

**Comment by rb-t** [comment]
Complete and done by Feb 10
