### ISSUE TITLE
3.2.1 Component Diagram

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project#66]
Todo:

Draw and explain the detailed design of the team's component:

1) that will be communicating with other parts of the project

![Image](https://user-images.githubusercontent.com/97349748/218651365-e3f38145-ac35-4090-b31c-3c2399896411.png)

Deadline: 11 Feb 2023, 12pm

**Comment by rb-t** [comment]
Our team will be interfacing with modules as below:
   Providing interface to: iDeviceLoggerService (M1-T4), iDeviceInfoService (M2-T5)
   Using interface from: iProfileService (M1-T2), iDeviceWattsService(M1-T4), ISendNotification (M2-T5)

We will be sending device logs information to M2-T5 for further analytics purposes and using interface from M2-T5 to get notifications to send devices energy limit when it is reached. We will be also taking profile information from M1-T2 to get devices under a profile and energy usage of each device from M1-T4. In conclusion, we will be working mainly with Module 1 and Module 2 teams. We will also be providing M1-T4 with a device logger service to start logs

The overall component diagram can be found under Figure 11 in the appendix.


Completed on 10 Feb
