### ISSUE TITLE
2.3 System Features

### ISSUE THREAD

**Issue by rylan98** [rawsashimi1604/ICT2106_P2_Project#67]
Todo:

1) List out and explain system features that were implemented based on user features requirement

Deadline: 11 Feb 2023, 12pm

**Comment by rb-t** [comment]
Feature 1,2,3



![Image](https://user-images.githubusercontent.com/90168622/218652990-97e25185-0f77-440e-96ad-991568b13fac.png)

**Comment by rb-t** [comment]
Features 4 & 5



![Image](https://user-images.githubusercontent.com/90168622/218653027-2e4f7745-2a67-4ccf-8524-267b45c47cc5.png)

**Comment by rb-t** [comment]
Done by Feb 10
