### ISSUE TITLE
Brainstorming Features

### ISSUE THREAD

**Issue by jianweiiii** [rawsashimi1604/ICT2106_P2_Project#7]

**Comment by 2102673** [comment]
All functional requirements:
Notifications
- The system must be able to display notifications to the user.
- When the total energy usage/spending threshold is hit, the system will send a notification to the user.
- The system should notify the user if a device is suspected to be faulty.


CarbonFootprint:
- The system should allow the user to check his total carbon footprint
- The system should allow the user to compare his total energy usage to the national household average energy usage.

EnergySpendingLimit:
- The system should allow the user to set their total energy usage/spending limit.
- The system should allow the user to set their total energy usage/spending threshold.

DataView:
- The system must be able to display energy/activity data to users.
- The system must be able to display energy/activity data of all devices.
- The system should allow the user to compare energy/activity usage data against different previous day/week/month total usage.
- The system should allow the user to compare energy/activity usage data against different devices and device brands.
- The system should allow the user to compare energy/activity usage data against different rooms.
- The system should allow the user to view abnormal energy usage spikes.
- The system should provide energy savings recommendations to the user, based on user habits.
- The system should display the user’s energy usage level by each profile

DataUpload
- The system will allow users to upload energy/usage data recorded from registered smart devices in the home.
- The system shall provide a page for users to upload data to.
- The system will allow users to upload data in the form of a .csv format.
- The system will allow users to upload multiple devices' energy/usage data at one go.
- The system should not allow users to upload energy/usage data of unregistered devices

DataPredictions
- The system should be able to forecast energy usage for the week/month based on the previous statistics collected.
- The system should be able to forecast total energy costs for the week/month based on the previous statistics collected.

DataReports
- The system should be able to generate an overall report for each device, which provides an overview of energy consumption and cost.
- The system should allow the users to download the report in PDF format.	


All Features
Users are able to receive notifications based on set events. 
Users are able to view energy usage/activity in various graphs displayed on a consolidated dashboard.
Users are able to compare energy usage/activity against different timespans, devices and rooms.
Users are able to compare energy usage between similar devices to spot anomalies. 
Users are able to compare energy usage between the past week usage to spot anomalies. 
Users are able to check their carbon footprint and compare it against nationwide household energy usage statistics.
Users are able to set energy usage/ spending limits and thresholds.
Users are able to analyse energy efficiency for each device based on energy/usage data.
Users can export reports of each device which provides an overview of energy consumption and cost in the form of a .pdf format.
Users are able to view forecasts of energy usage and cost for the week/month.
Users are able to view their user’s energy usage level in their own profiles.
Users are able to receive notifications if a device is suspected to be faulty.
