### ISSUE TITLE
3.2.2 Class Diagram

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project#70]
To do:

Draw and explain the detailed design of the team's detailed components:

1) that make up the system
2) to model the relationships between related components
3) to describe what those objects do and the services that they provide.

![Image](https://user-images.githubusercontent.com/97349748/218652977-1f955047-113a-4fcb-8d05-d123306629ac.png)

Deadline: 11 Feb 2023, 12pm

**Comment by rylan98** [comment]
Done by 10/2/2023
